---
sudo: required

notifications:
  email: false

services:
  - docker

env:
  matrix:
    - env:
      VERSION: '9.11.1'
    - env:
      VERSION: '8.11.1'
    - env:
      VERSION: '6.14.1'
    - env:
      VERSION: '4.9.1'

install:
  - docker build -t "lgatica/node-krb5-gm:$VERSION" "$VERSION"

script:
  - docker run --rm "lgatica/node-krb5-gm:$VERSION" node --version
