---
sudo: required

notifications:
  email: false

services:
  - docker

env:
  matrix:
    - env:
      VERSION: '8.1.2'
    - env:
      VERSION: '6.11.0'
    - env:
      VERSION: '4.8.6'

install:
  - docker build -t "lgatica/node-krb5-gm:$VERSION" "$VERSION"

script:
  - docker run --rm "lgatica/node-krb5-gm:$VERSION" node --version
